import Head from "next/head";
import Image from "next/image";
import Nav from "../components/user/Nav";
import Script from "next/script";
import UserLayout from "../components/user/UserLayout";
import Link from "next/dist/client/link";
import { useRouter } from "next/router";
import nim from "../pages/user/[nim]";

export default function Home() {
  const mahasiswa = [
    { nim: "1120", nama: "rian" },
    { nim: "1121", nama: "alex" },
    { nim: "1122", nama: "andre" },
  ];
  const router = useRouter();
  const sendParamRouter = (nim) => {
    router.push(`/user/${nim}`);
  };
  return (
    <div className={"container"}>
      <Nav />
      <Head>
        <title>Aplikasi Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
        <h3>Daftar Mahasiswa</h3>
        <ul>
          {mahasiswa.map((mhs, idx) => (
            <>
              <li key={idx}>
                <Link href={`/user/${mhs.nim}`}>
                  <a> {mhs.nim}</a>
                </Link>
                <p>{mhs.nama}</p>
                <button className="btn btn-primary" onClick={(e) => sendParamRouter(mhs.nim)}>
                  Cek Nilai
                </button>
              </li>
            </>
          ))}
        </ul>
      </main>

      <footer>
        <h4>Footer</h4>
      </footer>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
    </div>
  );
}
